### PR TITLE
Factorial program added

### PR DESCRIPTION
**Pull request by Pratik180198**
I had added the factorial program by solving it with two methods using FOR LOOP and RECURSIVE METHOD.
Sir please there is one more request that is just add a label in your About as 'HactoberFest' as I my participating in it.

### CODE REVIEW

**Review by pythonites — CHANGES_REQUESTED** [review]
Hello @Pratik180198 
Happy to see your contribution towards Open-source 😀
As you have used two different approaches to find the facrorial, please write two different programs and then make a pull request. 
 
regards @pythonites

**Comment by beertocode** [comment]
Please assign me this issue.

**Comment by Pratik180198** [comment]
Ok no problem I will add two different program for factorial.

**Comment by pythonites** [comment]
Similar PR found!!

**Pull request closed without merging**
